name: 'Qiniu Upload v2'
branding:
  icon: 'upload-cloud'
  color: 'blue'
description: 'github action for uploading files to qiniu'
author: 'Jiulong Hu'
inputs:
  access_key:
    description: 'access key'
    required: true
  secret_key:
    description: 'secret key'
    required: true
  bucket:
    description: 'bucket'
    required: true
  source_dir:
    description: 'source dir'
    default: './'
    required: false
  dest_dir:
    description: 'dest dir, namely key prefix'
    default: '/'
    required: false
  overwrite:
    description: 'overwrite strategy: always, never, smart (default: smart - overwrites code files but skips media files)'
    default: 'smart'
    required: false
  overwrite_patterns:
    description: 'custom glob patterns for files to always overwrite (comma-separated)'
    required: false
  skip_patterns:
    description: 'custom glob patterns for files to always skip (comma-separated)'
    required: false
  ignore_source_map:
    description: 'ignore source maps'
    default: true
    required: false
  concurrency:
    description: 'upload concurrency'
    default: '5'
    required: false
runs:
  using: 'node20'
  main: 'dist/index.js'
